name: Latest blog post workflow
on:
  schedule:
    # Runs every minute
    - cron: '* * * * *'
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: luannndev/blog-post-workflow@main
        with:
          feed_list: 'https://dev.to/feed/luannndev'