name: Latest blog post workflow
on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - "main"

jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          feed_list: 'https://dev.to/feed/luannndev'
          gh_token: ${{ secrets.GH_PAT }}
