name: Update Wakatime Readme

on:
  workflow_dispatch:
  schedule:
    - cron: "*/5 * * * *"

permissions: write-all

jobs:
  update-readme:
    name: Updates README
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master 
        with:
          GH_TOKEN: ${{ secrets.GH_TOKEN }} 
          SHOW_LINES_OF_CODE: "True"
          SHOW_LOC_CHART: "False" 
          SHOW_OS: "False"
          SHOW_TOTAL_CODE_TIME: "False"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
          SHOW_LANGUAGE: "False"
          SHOW_TIMEZONE: "False"
          COMMIT_MESSAGE: "Update Wakatime Activity"
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
